enyo.depends(
	"$lib/layout",
	"$lib/onyx",
  "crypto-sha256.js",
  "baito-main.js",
  "baito-main.css",
  "baito-components.js",
  "baito-components.css",
  "baito-myaccount-components.js",
  "baito-myaccount-components.css"
);
